### PR TITLE
Refactor

### PR DESCRIPTION
**Pull request by brancengregory**

### CODE REVIEW

**Review by AnthonyOKC — APPROVED** [review]
Ran fine for me! I also reformatted city council and school districts code so it matched the other geographies use of underscores.

**Review by AnthonyOKC — DISMISSED** [review]
Forgot I needed to manually unstage the cached sandbox folder. All good now.

**Comment by brancengregory** [comment]
We can scramble ids quickly with this:

```digest::digest(., algo = "xxhash64")```

**Review by AnthonyOKC — COMMENTED** [review]
👍

**Review by AnthonyOKC — APPROVED** [review]

**Pull request merged**
